# modules/PulsR/SportabzeichenBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # 1. Den Service explizit oder per Ordner-Struktur laden
    PulsR\SportabzeichenBundle\Service\:
        resource: '../../Service/*'
        
    PulsR\SportabzeichenBundle\EventListener\MenuListener:
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: kernel.event_listener, event: iserv.menu.main, method: onBuildMainMenu}

    PulsR\SportabzeichenBundle\Controller\:
        resource: '../../*'
        public: true
        tags: ['controller.service_arguments']

    PulsR\SportabzeichenBundle\Repository\:
        resource: '../../Repository'
        
 #   PulsR\SportabzeichenBundle\Crud\:
 #       resource: '../../Crud/*'
 #       public: true
 #       tags: ['iserv.crud']
 #       autowire: true
 #       autoconfigure: true
